version: '3.3'
services:
  jenkins:
    image: "jenkins/jenkins:lts"
    networks:
      - build_net
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "$HOME:/home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin/docker:/usr/bin/docker"

  artifactory:
    image: "docker.bintray.io/jfrog/artifactory-oss"
    networks:
      - build_net
    ports:
      - "8081:8081"

volumes:
  jenkins:
networks:
  build_net:
